export enum UserBehaviorEventEnum {
  SIGN_UP_PHONE = 'SIGN_UP_PHONE', // 手机号注册
  SIGN_UP_EMAIL = 'SIGN_UP_EMAIL', // 邮箱注册

  PHONE_MODIFY_PASSWORD_BY_PHONE_SUBMIT = 'MODIFY_PASSWORD_BY_PHONE', // "手机验证修改密码"
  PHONE_MODIFY_PASSWORD_BY_PHONE_SEND_CODE = 'MODIFY_PASSWORD_BYPHONE_SEND_CODE', // "发送修改手机密码验证码"
  EMAIL_MODIFY_PASSWORD_BY_EMAIL_SUBMIT = 'MODIFY_PASSWORD_BY_EMAIL', // "邮箱验证修改密码"
  EMAIL_MODIFY_PASSWORD_BY_EMAIL_SEND_CODE = 'MODIFY_PASSWORD_SEND_RESET_EMAIL', // "发送重置密码邮件"

  PHONE_MODIFY_PHONE_SUBMIT = 'MODIFY_PHONE', // "修改手机号"
  PHONE_MODIFY_PHONE_OLD_PHONE_CODE = 'MODIFY_PHONE_OLD_PHONE_CODE', // "发送修改手机号-原手机验证码"
  EMAIL_MODIFY_PHONE_SEND_EMAIL_CODE = 'MODIFY_PHONE_SEND_EMAIL', // "发送修改手机号-邮箱验证码"
  PHONE_MODIFY_PHONE_NEW_PHONE_CODE = 'MODIFY_PHONE_NEW_PHONE_CODE', // "发送修改手机号-新手机验证码"

  EMAIL_MODIFY_EMAIL_SUBMIT = 'MODIFY_EMAIL', // "修改邮箱", "修改邮箱"),
  EMAIL_MODIFY_EMAIL_SEND_OLD_EMAIL = 'MODIFY_EMAIL_SEND_OLD_EMAIL', // "修改邮箱-发送原邮箱确认邮件"
  PHONE_MODIFY_EMAIL_SEND_PHONE_CODE = 'MODIFY_EMAIL_SEND_PHONE_CODE', // "修改邮箱-手机验证码"
  EMAIL_MODIFY_EMAIL_SEND_NEW_EMAIL = 'MODIFY_EMAIL_SEND_NEW_EMAIL', // "修改邮箱-发送新邮箱确认邮件"

  PHONE_ADD_CORP_SEND_PHONE_CODE = 'ADD_CORP_SEND_PHONE_CODE', // "加入团队手机验证码"
  EMAIL_ADD_CORP_SEND_EMAIL_CODE = 'ADD_CORP_SEND_EMAIL_CODE', // "加入团队邮件验证码"

  PHONE_LOGIN_BY_PHONE_CODE = 'LOGIN_BY_PHONE_CODE', // 手机验证码登录
  PHONE_SEND_LOGIN_BY_PHONE_CODE = 'SEND_LOGIN_BY_PHONE_CODE', // 发送手机验证码
  EMAIL_LOGIN_BY_EMAIL_CODE = 'LOGIN_BY_EMAIL_CODE', // 邮箱验证码登录
  EMAIL_SEND_LOGIN_BY_EMAIL_CODE = 'SEND_LOGIN_BY_EMAIL_CODE' // 发送邮箱验证码
}
