import { DEFAULT_PREFIX } from '../../../mount';
import { prefix } from './constant';

export const defaultSuccessCSSVars = {
  // default-success
  'default-success-background': `var(--${prefix}-background)`,
  'default-success-border-width': `var(--${prefix}-border-width)`,
  'default-success-border-style': `var(--${prefix}-border-style)`,
  'default-success-border-color': `var(--${DEFAULT_PREFIX}-success-color)`,
  'default-success-border-radius': `var(--${prefix}-border-radius)`,
  'default-success-outline': 'none',
  'default-success-shadow': 'none',
  'default-success-text-color': `var(--${DEFAULT_PREFIX}-success-color)`,
  // default-success-active
  'default-success-background-active': `var(--${prefix}-default-success-background)`,
  'default-success-border-width-active': `var(--${prefix}-default-success-border-width)`,
  'default-success-border-style-active': `var(--${prefix}-default-success-border-style)`,
  'default-success-border-color-active': `var(--${DEFAULT_PREFIX}-success-color-active)`,
  'default-success-border-radius-active': `var(--${prefix}-default-success-border-radius)`,
  'default-success-outline-active': `var(--${prefix}-default-success-outline)`,
  'default-success-shadow-active': `var(--${prefix}-default-success-shadow)`,
  'default-success-text-color-active': `var(--${DEFAULT_PREFIX}-success-color-active)`,
  // default-success-focus
  'default-success-background-focus': `var(--${prefix}-default-success-background)`,
  'default-success-border-width-focus': `var(--${prefix}-default-success-border-width)`,
  'default-success-border-style-focus': `var(--${prefix}-default-success-border-style)`,
  'default-success-border-color-focus': `var(--${DEFAULT_PREFIX}-success-color-focus)`,
  'default-success-border-radius-focus': `var(--${prefix}-default-success-border-radius)`,
  'default-success-outline-focus': `var(--${prefix}-default-success-outline)`,
  'default-success-shadow-focus': `var(--${prefix}-default-success-shadow)`,
  'default-success-text-color-focus': `var(--${DEFAULT_PREFIX}-success-color-focus)`,
  // default-success-hover
  'default-success-background-hover': `var(--${prefix}-default-success-background)`,
  'default-success-border-width-hover': `var(--${prefix}-default-success-border-width)`,
  'default-success-border-style-hover': `var(--${prefix}-default-success-border-style)`,
  'default-success-border-color-hover': `var(--${DEFAULT_PREFIX}-success-color-hover)`,
  'default-success-border-radius-hover': `var(--${prefix}-default-success-border-radius)`,
  'default-success-outline-hover': `var(--${prefix}-default-success-outline)`,
  'default-success-shadow-hover': `var(--${prefix}-default-success-shadow)`,
  'default-success-text-color-hover': `var(--${DEFAULT_PREFIX}-success-color-hover)`,
  // default-success-visited
  'default-success-background-visited': `var(--${prefix}-default-success-background)`,
  'default-success-border-width-visited': `var(--${prefix}-default-success-border-width)`,
  'default-success-border-style-visited': `var(--${prefix}-default-success-border-style)`,
  'default-success-border-color-visited': `var(--${prefix}-default-success-border-color)`,
  'default-success-border-radius-visited': `var(--${prefix}-default-success-border-radius)`,
  'default-success-outline-visited': `var(--${prefix}-default-success-outline)`,
  'default-success-shadow-visited': `var(--${prefix}-default-success-shadow)`,
  'default-success-text-color-visited': `var(--${prefix}-default-success-text-color)`
};

export const primarySuccessCSSVars = {
  // primary-success
  'primary-success-background': `var(--${DEFAULT_PREFIX}-success-color)`,
  'primary-success-border-width': `var(--${prefix}-primary-border-width)`,
  'primary-success-border-style': `var(--${prefix}-primary-border-style)`,
  'primary-success-border-color': `var(--${DEFAULT_PREFIX}-success-color)`,
  'primary-success-border-radius': `var(--${prefix}-primary-border-radius)`,
  'primary-success-outline': 'none',
  'primary-success-shadow': 'none',
  'primary-success-text-color': '#ffffff',
  // primary-success-active
  'primary-success-background-active': `var(--${DEFAULT_PREFIX}-success-color-active)`,
  'primary-success-border-width-active': `var(--${prefix}-primary-success-border-width)`,
  'primary-success-border-style-active': `var(--${prefix}-primary-success-border-style)`,
  'primary-success-border-color-active': `var(--${DEFAULT_PREFIX}-success-color-active)`,
  'primary-success-border-radius-active': `var(--${prefix}-primary-success-border-radius)`,
  'primary-success-outline-active': `var(--${prefix}-primary-success-outline)`,
  'primary-success-shadow-active': `var(--${prefix}-primary-success-shadow)`,
  'primary-success-text-color-active': `var(--${prefix}-primary-success-text-color)`,
  // primary-success-focus
  'primary-success-background-focus': `var(--${DEFAULT_PREFIX}-success-color-focus)`,
  'primary-success-border-width-focus': `var(--${prefix}-primary-success-border-width)`,
  'primary-success-border-style-focus': `var(--${prefix}-primary-success-border-style)`,
  'primary-success-border-color-focus': `var(--${DEFAULT_PREFIX}-success-color-focus)`,
  'primary-success-border-radius-focus': `var(--${prefix}-primary-success-border-radius)`,
  'primary-success-outline-focus': `var(--${prefix}-primary-success-outline)`,
  'primary-success-shadow-focus': `var(--${prefix}-primary-success-shadow)`,
  'primary-success-text-color-focus': `var(--${prefix}-primary-success-text-color)`,
  // primary-success-hover
  'primary-success-background-hover': `var(--${DEFAULT_PREFIX}-success-color-hover)`,
  'primary-success-border-width-hover': `var(--${prefix}-primary-success-border-width)`,
  'primary-success-border-style-hover': `var(--${prefix}-primary-success-border-style)`,
  'primary-success-border-color-hover': `var(--${DEFAULT_PREFIX}-success-color-hover)`,
  'primary-success-border-radius-hover': `var(--${prefix}-primary-success-border-radius)`,
  'primary-success-outline-hover': `var(--${prefix}-primary-success-outline)`,
  'primary-success-shadow-hover': `var(--${prefix}-primary-success-shadow)`,
  'primary-success-text-color-hover': `var(--${prefix}-primary-success-text-color)`,
  // primary-success-visited
  'primary-success-background-visited': `var(--${prefix}-primary-success-background)`,
  'primary-success-border-width-visited': `var(--${prefix}-primary-success-border-width)`,
  'primary-success-border-style-visited': `var(--${prefix}-primary-success-border-style)`,
  'primary-success-border-color-visited': `var(--${prefix}-primary-success-border-color)`,
  'primary-success-border-radius-visited': `var(--${prefix}-primary-success-border-radius)`,
  'primary-success-outline-visited': `var(--${prefix}-primary-success-outline)`,
  'primary-success-shadow-visited': `var(--${prefix}-primary-success-shadow)`,
  'primary-success-text-color-visited': `var(--${prefix}-primary-success-text-color)`
};

export const linkSuccessCSSVars = {
  // link-success
  'link-success-background': `var(--${prefix}-link-background)`,
  'link-success-border-width': `var(--${prefix}-link-border-width)`,
  'link-success-border-style': `var(--${prefix}-link-border-style)`,
  'link-success-border-color': `var(--${prefix}-link-border-color)`,
  'link-success-border-radius': `var(--${prefix}-link-border-radius)`,
  'link-success-outline': 'none',
  'link-success-shadow': 'none',
  'link-success-text-color': `var(--${DEFAULT_PREFIX}-success-color)`,
  // link-success-active
  'link-success-background-active': `var(--${prefix}-link-success-color)`,
  'link-success-border-width-active': `var(--${prefix}-link-success-border-width)`,
  'link-success-border-style-active': `var(--${prefix}-link-success-border-style)`,
  'link-success-border-color-active': `var(--${prefix}-link-success-color)`,
  'link-success-border-radius-active': `var(--${prefix}-link-success-border-radius)`,
  'link-success-outline-active': `var(--${prefix}-link-success-outline)`,
  'link-success-shadow-active': `var(--${prefix}-link-success-shadow)`,
  'link-success-text-color-active': `var(--${DEFAULT_PREFIX}-success-color-active)`,
  // link-success-focus
  'link-success-background-focus': `var(--${prefix}-link-success-color)`,
  'link-success-border-width-focus': `var(--${prefix}-link-success-border-width)`,
  'link-success-border-style-focus': `var(--${prefix}-link-success-border-style)`,
  'link-success-border-color-focus': `var(--${prefix}-link-success-color)`,
  'link-success-border-radius-focus': `var(--${prefix}-link-success-border-radius)`,
  'link-success-outline-focus': `var(--${prefix}-link-success-outline)`,
  'link-success-shadow-focus': `var(--${prefix}-link-success-shadow)`,
  'link-success-text-color-focus': `var(--${DEFAULT_PREFIX}-success-color-focus)`,
  // link-success-hover
  'link-success-background-hover': `var(--${prefix}-link-success-color)`,
  'link-success-border-width-hover': `var(--${prefix}-link-success-border-width)`,
  'link-success-border-style-hover': `var(--${prefix}-link-success-border-style)`,
  'link-success-border-color-hover': `var(--${prefix}-link-success-color)`,
  'link-success-border-radius-hover': `var(--${prefix}-link-success-border-radius)`,
  'link-success-outline-hover': `var(--${prefix}-link-success-outline)`,
  'link-success-shadow-hover': `var(--${prefix}-link-success-shadow)`,
  'link-success-text-color-hover': `var(--${DEFAULT_PREFIX}-success-color-hover)`,
  // link-success-visited
  'link-success-background-visited': `var(--${prefix}-link-success-background)`,
  'link-success-border-width-visited': `var(--${prefix}-link-success-border-width)`,
  'link-success-border-style-visited': `var(--${prefix}-link-success-border-style)`,
  'link-success-border-color-visited': `var(--${prefix}-link-success-border-color)`,
  'link-success-border-radius-visited': `var(--${prefix}-link-success-border-radius)`,
  'link-success-outline-visited': `var(--${prefix}-link-success-outline)`,
  'link-success-shadow-visited': `var(--${prefix}-link-success-shadow)`,
  'link-success-text-color-visited': `var(--${prefix}-link-success-text-color)`
};
