import { DEFAULT_PREFIX } from '../../../mount';
import { prefix } from './constant';

export const defaultWarningCSSVars = {
  // default-warning
  'default-warning-background': `var(--${prefix}-background)`,
  'default-warning-border-width': `var(--${prefix}-border-width)`,
  'default-warning-border-style': `var(--${prefix}-border-style)`,
  'default-warning-border-color': `var(--${DEFAULT_PREFIX}-warning-color)`,
  'default-warning-border-radius': `var(--${prefix}-border-radius)`,
  'default-warning-outline': 'none',
  'default-warning-shadow': 'none',
  'default-warning-text-color': `var(--${DEFAULT_PREFIX}-warning-color)`,
  // default-warning-active
  'default-warning-background-active': `var(--${prefix}-default-warning-background)`,
  'default-warning-border-width-active': `var(--${prefix}-default-warning-border-width)`,
  'default-warning-border-style-active': `var(--${prefix}-default-warning-border-style)`,
  'default-warning-border-color-active': `var(--${DEFAULT_PREFIX}-warning-color-active)`,
  'default-warning-border-radius-active': `var(--${prefix}-default-warning-border-radius)`,
  'default-warning-outline-active': `var(--${prefix}-default-warning-outline)`,
  'default-warning-shadow-active': `var(--${prefix}-default-warning-shadow)`,
  'default-warning-text-color-active': `var(--${DEFAULT_PREFIX}-warning-color-active)`,
  // default-warning-focus
  'default-warning-background-focus': `var(--${prefix}-default-warning-background)`,
  'default-warning-border-width-focus': `var(--${prefix}-default-warning-border-width)`,
  'default-warning-border-style-focus': `var(--${prefix}-default-warning-border-style)`,
  'default-warning-border-color-focus': `var(--${DEFAULT_PREFIX}-warning-color-focus)`,
  'default-warning-border-radius-focus': `var(--${prefix}-default-warning-border-radius)`,
  'default-warning-outline-focus': `var(--${prefix}-default-warning-outline)`,
  'default-warning-shadow-focus': `var(--${prefix}-default-warning-shadow)`,
  'default-warning-text-color-focus': `var(--${DEFAULT_PREFIX}-warning-color-focus)`,
  // default-warning-hover
  'default-warning-background-hover': `var(--${prefix}-default-warning-background)`,
  'default-warning-border-width-hover': `var(--${prefix}-default-warning-border-width)`,
  'default-warning-border-style-hover': `var(--${prefix}-default-warning-border-style)`,
  'default-warning-border-color-hover': `var(--${DEFAULT_PREFIX}-warning-color-hover)`,
  'default-warning-border-radius-hover': `var(--${prefix}-default-warning-border-radius)`,
  'default-warning-outline-hover': `var(--${prefix}-default-warning-outline)`,
  'default-warning-shadow-hover': `var(--${prefix}-default-warning-shadow)`,
  'default-warning-text-color-hover': `var(--${DEFAULT_PREFIX}-warning-color-hover)`,
  // default-warning-visited
  'default-warning-background-visited': `var(--${prefix}-default-warning-background)`,
  'default-warning-border-width-visited': `var(--${prefix}-default-warning-border-width)`,
  'default-warning-border-style-visited': `var(--${prefix}-default-warning-border-style)`,
  'default-warning-border-color-visited': `var(--${prefix}-default-warning-border-color)`,
  'default-warning-border-radius-visited': `var(--${prefix}-default-warning-border-radius)`,
  'default-warning-outline-visited': `var(--${prefix}-default-warning-outline)`,
  'default-warning-shadow-visited': `var(--${prefix}-default-warning-shadow)`,
  'default-warning-text-color-visited': `var(--${prefix}-default-warning-text-color)`
};

export const primaryWarningCSSVars = {
  // primary-warning
  'primary-warning-background': `var(--${DEFAULT_PREFIX}-warning-color)`,
  'primary-warning-border-width': `var(--${prefix}-primary-border-width)`,
  'primary-warning-border-style': `var(--${prefix}-primary-border-style)`,
  'primary-warning-border-color': `var(--${DEFAULT_PREFIX}-warning-color)`,
  'primary-warning-border-radius': `var(--${prefix}-primary-border-radius)`,
  'primary-warning-outline': 'none',
  'primary-warning-shadow': 'none',
  'primary-warning-text-color': '#ffffff',
  // primary-warning-active
  'primary-warning-background-active': `var(--${DEFAULT_PREFIX}-warning-color-active)`,
  'primary-warning-border-width-active': `var(--${prefix}-primary-warning-border-width)`,
  'primary-warning-border-style-active': `var(--${prefix}-primary-warning-border-style)`,
  'primary-warning-border-color-active': `var(--${DEFAULT_PREFIX}-warning-color-active)`,
  'primary-warning-border-radius-active': `var(--${prefix}-primary-warning-border-radius)`,
  'primary-warning-outline-active': `var(--${prefix}-primary-warning-outline)`,
  'primary-warning-shadow-active': `var(--${prefix}-primary-warning-shadow)`,
  'primary-warning-text-color-active': `var(--${prefix}-primary-warning-text-color)`,
  // primary-warning-focus
  'primary-warning-background-focus': `var(--${DEFAULT_PREFIX}-warning-color-focus)`,
  'primary-warning-border-width-focus': `var(--${prefix}-primary-warning-border-width)`,
  'primary-warning-border-style-focus': `var(--${prefix}-primary-warning-border-style)`,
  'primary-warning-border-color-focus': `var(--${DEFAULT_PREFIX}-warning-color-focus)`,
  'primary-warning-border-radius-focus': `var(--${prefix}-primary-warning-border-radius)`,
  'primary-warning-outline-focus': `var(--${prefix}-primary-warning-outline)`,
  'primary-warning-shadow-focus': `var(--${prefix}-primary-warning-shadow)`,
  'primary-warning-text-color-focus': `var(--${prefix}-primary-warning-text-color)`,
  // primary-warning-hover
  'primary-warning-background-hover': `var(--${DEFAULT_PREFIX}-warning-color-hover)`,
  'primary-warning-border-width-hover': `var(--${prefix}-primary-warning-border-width)`,
  'primary-warning-border-style-hover': `var(--${prefix}-primary-warning-border-style)`,
  'primary-warning-border-color-hover': `var(--${DEFAULT_PREFIX}-warning-color-hover)`,
  'primary-warning-border-radius-hover': `var(--${prefix}-primary-warning-border-radius)`,
  'primary-warning-outline-hover': `var(--${prefix}-primary-warning-outline)`,
  'primary-warning-shadow-hover': `var(--${prefix}-primary-warning-shadow)`,
  'primary-warning-text-color-hover': `var(--${prefix}-primary-warning-text-color)`,
  // primary-warning-visited
  'primary-warning-background-visited': `var(--${prefix}-primary-warning-background)`,
  'primary-warning-border-width-visited': `var(--${prefix}-primary-warning-border-width)`,
  'primary-warning-border-style-visited': `var(--${prefix}-primary-warning-border-style)`,
  'primary-warning-border-color-visited': `var(--${prefix}-primary-warning-border-color)`,
  'primary-warning-border-radius-visited': `var(--${prefix}-primary-warning-border-radius)`,
  'primary-warning-outline-visited': `var(--${prefix}-primary-warning-outline)`,
  'primary-warning-shadow-visited': `var(--${prefix}-primary-warning-shadow)`,
  'primary-warning-text-color-visited': `var(--${prefix}-primary-warning-text-color)`
};

export const linkWarningCSSVars = {
  // link-warning
  'link-warning-background': `var(--${prefix}-link-background)`,
  'link-warning-border-width': `var(--${prefix}-link-border-width)`,
  'link-warning-border-style': `var(--${prefix}-link-border-style)`,
  'link-warning-border-color': `var(--${prefix}-link-border-color)`,
  'link-warning-border-radius': `var(--${prefix}-link-border-radius)`,
  'link-warning-outline': 'none',
  'link-warning-shadow': 'none',
  'link-warning-text-color': `var(--${DEFAULT_PREFIX}-warning-color)`,
  // link-warning-active
  'link-warning-background-active': `var(--${prefix}-link-warning-color)`,
  'link-warning-border-width-active': `var(--${prefix}-link-warning-border-width)`,
  'link-warning-border-style-active': `var(--${prefix}-link-warning-border-style)`,
  'link-warning-border-color-active': `var(--${prefix}-link-warning-color)`,
  'link-warning-border-radius-active': `var(--${prefix}-link-warning-border-radius)`,
  'link-warning-outline-active': `var(--${prefix}-link-warning-outline)`,
  'link-warning-shadow-active': `var(--${prefix}-link-warning-shadow)`,
  'link-warning-text-color-active': `var(--${DEFAULT_PREFIX}-warning-color-active)`,
  // link-warning-focus
  'link-warning-background-focus': `var(--${prefix}-link-warning-color)`,
  'link-warning-border-width-focus': `var(--${prefix}-link-warning-border-width)`,
  'link-warning-border-style-focus': `var(--${prefix}-link-warning-border-style)`,
  'link-warning-border-color-focus': `var(--${prefix}-link-warning-color)`,
  'link-warning-border-radius-focus': `var(--${prefix}-link-warning-border-radius)`,
  'link-warning-outline-focus': `var(--${prefix}-link-warning-outline)`,
  'link-warning-shadow-focus': `var(--${prefix}-link-warning-shadow)`,
  'link-warning-text-color-focus': `var(--${DEFAULT_PREFIX}-warning-color-focus)`,
  // link-warning-hover
  'link-warning-background-hover': `var(--${prefix}-link-warning-color)`,
  'link-warning-border-width-hover': `var(--${prefix}-link-warning-border-width)`,
  'link-warning-border-style-hover': `var(--${prefix}-link-warning-border-style)`,
  'link-warning-border-color-hover': `var(--${prefix}-link-warning-color)`,
  'link-warning-border-radius-hover': `var(--${prefix}-link-warning-border-radius)`,
  'link-warning-outline-hover': `var(--${prefix}-link-warning-outline)`,
  'link-warning-shadow-hover': `var(--${prefix}-link-warning-shadow)`,
  'link-warning-text-color-hover': `var(--${DEFAULT_PREFIX}-warning-color-hover)`,
  // link-warning-visited
  'link-warning-background-visited': `var(--${prefix}-link-warning-background)`,
  'link-warning-border-width-visited': `var(--${prefix}-link-warning-border-width)`,
  'link-warning-border-style-visited': `var(--${prefix}-link-warning-border-style)`,
  'link-warning-border-color-visited': `var(--${prefix}-link-warning-border-color)`,
  'link-warning-border-radius-visited': `var(--${prefix}-link-warning-border-radius)`,
  'link-warning-outline-visited': `var(--${prefix}-link-warning-outline)`,
  'link-warning-shadow-visited': `var(--${prefix}-link-warning-shadow)`,
  'link-warning-text-color-visited': `var(--${prefix}-link-warning-text-color)`
};
