cache:
  paths:
    - node_modules/

before_script:
  - npm i

stages:
  - lint_only_mr

lint_staged:
  stage: lint_only_mr
  except:
    - branches
    - tags
    - pushes
  script:
    - npm run lint
