import { DEFAULT_PREFIX } from '../../../mount';
import { prefix } from './constant';

export const defaultInfoCSSVars = {
  // default-info
  'default-info-background': `var(--${prefix}-background)`,
  'default-info-border-width': `var(--${prefix}-border-width)`,
  'default-info-border-style': `var(--${prefix}-border-style)`,
  'default-info-border-color': `var(--${DEFAULT_PREFIX}-info-color)`,
  'default-info-border-radius': `var(--${prefix}-border-radius)`,
  'default-info-outline': 'none',
  'default-info-shadow': 'none',
  'default-info-text-color': `var(--${DEFAULT_PREFIX}-info-color)`,
  // default-info-active
  'default-info-background-active': `var(--${prefix}-default-info-background)`,
  'default-info-border-width-active': `var(--${prefix}-default-info-border-width)`,
  'default-info-border-style-active': `var(--${prefix}-default-info-border-style)`,
  'default-info-border-color-active': `var(--${DEFAULT_PREFIX}-info-color-active)`,
  'default-info-border-radius-active': `var(--${prefix}-default-info-border-radius)`,
  'default-info-outline-active': `var(--${prefix}-default-info-outline)`,
  'default-info-shadow-active': `var(--${prefix}-default-info-shadow)`,
  'default-info-text-color-active': `var(--${DEFAULT_PREFIX}-info-color-active)`,
  // default-info-focus
  'default-info-background-focus': `var(--${prefix}-default-info-background)`,
  'default-info-border-width-focus': `var(--${prefix}-default-info-border-width)`,
  'default-info-border-style-focus': `var(--${prefix}-default-info-border-style)`,
  'default-info-border-color-focus': `var(--${DEFAULT_PREFIX}-info-color-focus)`,
  'default-info-border-radius-focus': `var(--${prefix}-default-info-border-radius)`,
  'default-info-outline-focus': `var(--${prefix}-default-info-outline)`,
  'default-info-shadow-focus': `var(--${prefix}-default-info-shadow)`,
  'default-info-text-color-focus': `var(--${DEFAULT_PREFIX}-info-color-focus)`,
  // default-info-hover
  'default-info-background-hover': `var(--${prefix}-default-info-background)`,
  'default-info-border-width-hover': `var(--${prefix}-default-info-border-width)`,
  'default-info-border-style-hover': `var(--${prefix}-default-info-border-style)`,
  'default-info-border-color-hover': `var(--${DEFAULT_PREFIX}-info-color-hover)`,
  'default-info-border-radius-hover': `var(--${prefix}-default-info-border-radius)`,
  'default-info-outline-hover': `var(--${prefix}-default-info-outline)`,
  'default-info-shadow-hover': `var(--${prefix}-default-info-shadow)`,
  'default-info-text-color-hover': `var(--${DEFAULT_PREFIX}-info-color-hover)`,
  // default-info-visited
  'default-info-background-visited': `var(--${prefix}-default-info-background)`,
  'default-info-border-width-visited': `var(--${prefix}-default-info-border-width)`,
  'default-info-border-style-visited': `var(--${prefix}-default-info-border-style)`,
  'default-info-border-color-visited': `var(--${prefix}-default-info-border-color)`,
  'default-info-border-radius-visited': `var(--${prefix}-default-info-border-radius)`,
  'default-info-outline-visited': `var(--${prefix}-default-info-outline)`,
  'default-info-shadow-visited': `var(--${prefix}-default-info-shadow)`,
  'default-info-text-color-visited': `var(--${prefix}-default-info-text-color)`
};

export const primaryInfoCSSVars = {
  // primary-info
  'primary-info-background': `var(--${DEFAULT_PREFIX}-info-color)`,
  'primary-info-border-width': `var(--${prefix}-primary-border-width)`,
  'primary-info-border-style': `var(--${prefix}-primary-border-style)`,
  'primary-info-border-color': `var(--${DEFAULT_PREFIX}-info-color)`,
  'primary-info-border-radius': `var(--${prefix}-primary-border-radius)`,
  'primary-info-outline': 'none',
  'primary-info-shadow': 'none',
  'primary-info-text-color': '#ffffff',
  // primary-info-active
  'primary-info-background-active': `var(--${DEFAULT_PREFIX}-info-color-active)`,
  'primary-info-border-width-active': `var(--${prefix}-primary-info-border-width)`,
  'primary-info-border-style-active': `var(--${prefix}-primary-info-border-style)`,
  'primary-info-border-color-active': `var(--${DEFAULT_PREFIX}-info-color-active)`,
  'primary-info-border-radius-active': `var(--${prefix}-primary-info-border-radius)`,
  'primary-info-outline-active': `var(--${prefix}-primary-info-outline)`,
  'primary-info-shadow-active': `var(--${prefix}-primary-info-shadow)`,
  'primary-info-text-color-active': `var(--${prefix}-primary-info-text-color)`,
  // primary-info-focus
  'primary-info-background-focus': `var(--${DEFAULT_PREFIX}-info-color-focus)`,
  'primary-info-border-width-focus': `var(--${prefix}-primary-info-border-width)`,
  'primary-info-border-style-focus': `var(--${prefix}-primary-info-border-style)`,
  'primary-info-border-color-focus': `var(--${DEFAULT_PREFIX}-info-color-focus)`,
  'primary-info-border-radius-focus': `var(--${prefix}-primary-info-border-radius)`,
  'primary-info-outline-focus': `var(--${prefix}-primary-info-outline)`,
  'primary-info-shadow-focus': `var(--${prefix}-primary-info-shadow)`,
  'primary-info-text-color-focus': `var(--${prefix}-primary-info-text-color)`,
  // primary-info-hover
  'primary-info-background-hover': `var(--${DEFAULT_PREFIX}-info-color-hover)`,
  'primary-info-border-width-hover': `var(--${prefix}-primary-info-border-width)`,
  'primary-info-border-style-hover': `var(--${prefix}-primary-info-border-style)`,
  'primary-info-border-color-hover': `var(--${DEFAULT_PREFIX}-info-color-hover)`,
  'primary-info-border-radius-hover': `var(--${prefix}-primary-info-border-radius)`,
  'primary-info-outline-hover': `var(--${prefix}-primary-info-outline)`,
  'primary-info-shadow-hover': `var(--${prefix}-primary-info-shadow)`,
  'primary-info-text-color-hover': `var(--${prefix}-primary-info-text-color)`,
  // primary-info-visited
  'primary-info-background-visited': `var(--${prefix}-primary-info-background)`,
  'primary-info-border-width-visited': `var(--${prefix}-primary-info-border-width)`,
  'primary-info-border-style-visited': `var(--${prefix}-primary-info-border-style)`,
  'primary-info-border-color-visited': `var(--${prefix}-primary-info-border-color)`,
  'primary-info-border-radius-visited': `var(--${prefix}-primary-info-border-radius)`,
  'primary-info-outline-visited': `var(--${prefix}-primary-info-outline)`,
  'primary-info-shadow-visited': `var(--${prefix}-primary-info-shadow)`,
  'primary-info-text-color-visited': `var(--${prefix}-primary-info-text-color)`
};

export const linkInfoCSSVars = {
  // link-info
  'link-info-background': `var(--${prefix}-link-background)`,
  'link-info-border-width': `var(--${prefix}-link-border-width)`,
  'link-info-border-style': `var(--${prefix}-link-border-style)`,
  'link-info-border-color': `var(--${prefix}-link-border-color)`,
  'link-info-border-radius': `var(--${prefix}-link-border-radius)`,
  'link-info-outline': 'none',
  'link-info-shadow': 'none',
  'link-info-text-color': `var(--${DEFAULT_PREFIX}-info-color)`,
  // link-info-active
  'link-info-background-active': `var(--${prefix}-link-info-color)`,
  'link-info-border-width-active': `var(--${prefix}-link-info-border-width)`,
  'link-info-border-style-active': `var(--${prefix}-link-info-border-style)`,
  'link-info-border-color-active': `var(--${prefix}-link-info-color)`,
  'link-info-border-radius-active': `var(--${prefix}-link-info-border-radius)`,
  'link-info-outline-active': `var(--${prefix}-link-info-outline)`,
  'link-info-shadow-active': `var(--${prefix}-link-info-shadow)`,
  'link-info-text-color-active': `var(--${DEFAULT_PREFIX}-info-color-active)`,
  // link-info-focus
  'link-info-background-focus': `var(--${prefix}-link-info-color)`,
  'link-info-border-width-focus': `var(--${prefix}-link-info-border-width)`,
  'link-info-border-style-focus': `var(--${prefix}-link-info-border-style)`,
  'link-info-border-color-focus': `var(--${prefix}-link-info-color)`,
  'link-info-border-radius-focus': `var(--${prefix}-link-info-border-radius)`,
  'link-info-outline-focus': `var(--${prefix}-link-info-outline)`,
  'link-info-shadow-focus': `var(--${prefix}-link-info-shadow)`,
  'link-info-text-color-focus': `var(--${DEFAULT_PREFIX}-info-color-focus)`,
  // link-info-hover
  'link-info-background-hover': `var(--${prefix}-link-info-color)`,
  'link-info-border-width-hover': `var(--${prefix}-link-info-border-width)`,
  'link-info-border-style-hover': `var(--${prefix}-link-info-border-style)`,
  'link-info-border-color-hover': `var(--${prefix}-link-info-color)`,
  'link-info-border-radius-hover': `var(--${prefix}-link-info-border-radius)`,
  'link-info-outline-hover': `var(--${prefix}-link-info-outline)`,
  'link-info-shadow-hover': `var(--${prefix}-link-info-shadow)`,
  'link-info-text-color-hover': `var(--${DEFAULT_PREFIX}-info-color-hover)`,
  // link-info-visited
  'link-info-background-visited': `var(--${prefix}-link-info-background)`,
  'link-info-border-width-visited': `var(--${prefix}-link-info-border-width)`,
  'link-info-border-style-visited': `var(--${prefix}-link-info-border-style)`,
  'link-info-border-color-visited': `var(--${prefix}-link-info-border-color)`,
  'link-info-border-radius-visited': `var(--${prefix}-link-info-border-radius)`,
  'link-info-outline-visited': `var(--${prefix}-link-info-outline)`,
  'link-info-shadow-visited': `var(--${prefix}-link-info-shadow)`,
  'link-info-text-color-visited': `var(--${prefix}-link-info-text-color)`
};
