import { DEFAULT_PREFIX } from '../../../mount';
import { prefix } from './constant';

export const defaultDangerCSSVars = {
  // default-danger
  'default-danger-background': `var(--${prefix}-background)`,
  'default-danger-border-width': `var(--${prefix}-border-width)`,
  'default-danger-border-style': `var(--${prefix}-border-style)`,
  'default-danger-border-color': `var(--${DEFAULT_PREFIX}-error-color)`,
  'default-danger-border-radius': `var(--${prefix}-border-radius)`,
  'default-danger-outline': `var(--${DEFAULT_PREFIX}-error-color-outline)`,
  'default-danger-shadow': 'none',
  'default-danger-text-color': `var(--${DEFAULT_PREFIX}-error-color)`,
  // default-danger-active
  'default-danger-background-active': `var(--${prefix}-default-danger-background)`,
  'default-danger-border-width-active': `var(--${prefix}-default-danger-border-width)`,
  'default-danger-border-style-active': `var(--${prefix}-default-danger-border-style)`,
  'default-danger-border-color-active': `var(--${DEFAULT_PREFIX}-error-color-active)`,
  'default-danger-border-radius-active': `var(--${prefix}-default-danger-border-radius)`,
  'default-danger-outline-active': `var(--${prefix}-default-danger-outline)`,
  'default-danger-shadow-active': `var(--${prefix}-default-danger-shadow)`,
  'default-danger-text-color-active': `var(--${DEFAULT_PREFIX}-error-color-active)`,
  // default-danger-focus
  'default-danger-background-focus': `var(--${prefix}-default-danger-background)`,
  'default-danger-border-width-focus': `var(--${prefix}-default-danger-border-width)`,
  'default-danger-border-style-focus': `var(--${prefix}-default-danger-border-style)`,
  'default-danger-border-color-focus': `var(--${DEFAULT_PREFIX}-error-color-focus)`,
  'default-danger-border-radius-focus': `var(--${prefix}-default-danger-border-radius)`,
  'default-danger-outline-focus': `var(--${prefix}-default-danger-outline)`,
  'default-danger-shadow-focus': `var(--${prefix}-default-danger-shadow)`,
  'default-danger-text-color-focus': `var(--${DEFAULT_PREFIX}-error-color-focus)`,
  // default-danger-hover
  'default-danger-background-hover': `var(--${prefix}-default-danger-background)`,
  'default-danger-border-width-hover': `var(--${prefix}-default-danger-border-width)`,
  'default-danger-border-style-hover': `var(--${prefix}-default-danger-border-style)`,
  'default-danger-border-color-hover': `var(--${DEFAULT_PREFIX}-error-color-hover)`,
  'default-danger-border-radius-hover': `var(--${prefix}-default-danger-border-radius)`,
  'default-danger-outline-hover': `var(--${prefix}-default-danger-outline)`,
  'default-danger-shadow-hover': `var(--${prefix}-default-danger-shadow)`,
  'default-danger-text-color-hover': `var(--${DEFAULT_PREFIX}-error-color-hover)`,
  // default-danger-visited
  'default-danger-background-visited': `var(--${prefix}-default-danger-background)`,
  'default-danger-border-width-visited': `var(--${prefix}-default-danger-border-width)`,
  'default-danger-border-style-visited': `var(--${prefix}-default-danger-border-style)`,
  'default-danger-border-color-visited': `var(--${prefix}-default-danger-border-color)`,
  'default-danger-border-radius-visited': `var(--${prefix}-default-danger-border-radius)`,
  'default-danger-outline-visited': `var(--${prefix}-default-danger-outline)`,
  'default-danger-shadow-visited': `var(--${prefix}-default-danger-shadow)`,
  'default-danger-text-color-visited': `var(--${prefix}-default-danger-text-color)`
};

export const primaryDangerCSSVars = {
  // primary-danger
  'primary-danger-background': `var(--${DEFAULT_PREFIX}-error-color)`,
  'primary-danger-border-width': `var(--${prefix}-primary-border-width)`,
  'primary-danger-border-style': `var(--${prefix}-primary-border-style)`,
  'primary-danger-border-color': `var(--${DEFAULT_PREFIX}-error-color)`,
  'primary-danger-border-radius': `var(--${prefix}-primary-border-radius)`,
  'primary-danger-outline': `var(--${DEFAULT_PREFIX}-error-color)`,
  'primary-danger-shadow': 'none',
  'primary-danger-text-color': '#ffffff',
  // primary-danger-active
  'primary-danger-background-active': `var(--${DEFAULT_PREFIX}-error-color-active)`,
  'primary-danger-border-width-active': `var(--${prefix}-primary-danger-border-width)`,
  'primary-danger-border-style-active': `var(--${prefix}-primary-danger-border-style)`,
  'primary-danger-border-color-active': `var(--${DEFAULT_PREFIX}-error-color-active)`,
  'primary-danger-border-radius-active': `var(--${prefix}-primary-danger-border-radius)`,
  'primary-danger-outline-active': `var(--${prefix}-primary-danger-outline)`,
  'primary-danger-shadow-active': `var(--${prefix}-primary-danger-shadow)`,
  'primary-danger-text-color-active': `var(--${prefix}-primary-danger-text-color)`,
  // primary-danger-focus
  'primary-danger-background-focus': `var(--${DEFAULT_PREFIX}-error-color-focus)`,
  'primary-danger-border-width-focus': `var(--${prefix}-primary-danger-border-width)`,
  'primary-danger-border-style-focus': `var(--${prefix}-primary-danger-border-style)`,
  'primary-danger-border-color-focus': `var(--${DEFAULT_PREFIX}-error-color-focus)`,
  'primary-danger-border-radius-focus': `var(--${prefix}-primary-danger-border-radius)`,
  'primary-danger-outline-focus': `var(--${prefix}-primary-danger-outline)`,
  'primary-danger-shadow-focus': `var(--${prefix}-primary-danger-shadow)`,
  'primary-danger-text-color-focus': `var(--${prefix}-primary-danger-text-color)`,
  // primary-danger-hover
  'primary-danger-background-hover': `var(--${DEFAULT_PREFIX}-error-color-hover)`,
  'primary-danger-border-width-hover': `var(--${prefix}-primary-danger-border-width)`,
  'primary-danger-border-style-hover': `var(--${prefix}-primary-danger-border-style)`,
  'primary-danger-border-color-hover': `var(--${DEFAULT_PREFIX}-error-color-hover)`,
  'primary-danger-border-radius-hover': `var(--${prefix}-primary-danger-border-radius)`,
  'primary-danger-outline-hover': `var(--${prefix}-primary-danger-outline)`,
  'primary-danger-shadow-hover': `var(--${prefix}-primary-danger-shadow)`,
  'primary-danger-text-color-hover': `var(--${prefix}-primary-danger-text-color)`,
  // primary-danger-visited
  'primary-danger-background-visited': `var(--${prefix}-primary-danger-background)`,
  'primary-danger-border-width-visited': `var(--${prefix}-primary-danger-border-width)`,
  'primary-danger-border-style-visited': `var(--${prefix}-primary-danger-border-style)`,
  'primary-danger-border-color-visited': `var(--${prefix}-primary-danger-border-color)`,
  'primary-danger-border-radius-visited': `var(--${prefix}-primary-danger-border-radius)`,
  'primary-danger-outline-visited': `var(--${prefix}-primary-danger-outline)`,
  'primary-danger-shadow-visited': `var(--${prefix}-primary-danger-shadow)`,
  'primary-danger-text-color-visited': `var(--${prefix}-primary-danger-text-color)`
};

export const linkDangerCSSVars = {
  // link-danger
  'link-danger-background': `var(--${prefix}-link-background)`,
  'link-danger-border-width': `var(--${prefix}-link-border-width)`,
  'link-danger-border-style': `var(--${prefix}-link-border-style)`,
  'link-danger-border-color': `var(--${prefix}-link-border-color)`,
  'link-danger-border-radius': `var(--${prefix}-link-border-radius)`,
  'link-danger-outline': 'none',
  'link-danger-shadow': 'none',
  'link-danger-text-color': `var(--${DEFAULT_PREFIX}-error-color)`,
  // link-danger-active
  'link-danger-background-active': `var(--${prefix}-link-danger-color)`,
  'link-danger-border-width-active': `var(--${prefix}-link-danger-border-width)`,
  'link-danger-border-style-active': `var(--${prefix}-link-danger-border-style)`,
  'link-danger-border-color-active': `var(--${prefix}-link-danger-color)`,
  'link-danger-border-radius-active': `var(--${prefix}-link-danger-border-radius)`,
  'link-danger-outline-active': `var(--${prefix}-link-danger-outline)`,
  'link-danger-shadow-active': `var(--${prefix}-link-danger-shadow)`,
  'link-danger-text-color-active': `var(--${DEFAULT_PREFIX}-error-color-active)`,
  // link-danger-focus
  'link-danger-background-focus': `var(--${prefix}-link-danger-color)`,
  'link-danger-border-width-focus': `var(--${prefix}-link-danger-border-width)`,
  'link-danger-border-style-focus': `var(--${prefix}-link-danger-border-style)`,
  'link-danger-border-color-focus': `var(--${prefix}-link-danger-color)`,
  'link-danger-border-radius-focus': `var(--${prefix}-link-danger-border-radius)`,
  'link-danger-outline-focus': `var(--${prefix}-link-danger-outline)`,
  'link-danger-shadow-focus': `var(--${prefix}-link-danger-shadow)`,
  'link-danger-text-color-focus': `var(--${DEFAULT_PREFIX}-error-color-focus)`,
  // link-danger-hover
  'link-danger-background-hover': `var(--${prefix}-link-danger-color)`,
  'link-danger-border-width-hover': `var(--${prefix}-link-danger-border-width)`,
  'link-danger-border-style-hover': `var(--${prefix}-link-danger-border-style)`,
  'link-danger-border-color-hover': `var(--${prefix}-link-danger-color)`,
  'link-danger-border-radius-hover': `var(--${prefix}-link-danger-border-radius)`,
  'link-danger-outline-hover': `var(--${prefix}-link-danger-outline)`,
  'link-danger-shadow-hover': `var(--${prefix}-link-danger-shadow)`,
  'link-danger-text-color-hover': `var(--${DEFAULT_PREFIX}-error-color-hover)`,
  // link-danger-visited
  'link-danger-background-visited': `var(--${prefix}-link-danger-background)`,
  'link-danger-border-width-visited': `var(--${prefix}-link-danger-border-width)`,
  'link-danger-border-style-visited': `var(--${prefix}-link-danger-border-style)`,
  'link-danger-border-color-visited': `var(--${prefix}-link-danger-border-color)`,
  'link-danger-border-radius-visited': `var(--${prefix}-link-danger-border-radius)`,
  'link-danger-outline-visited': `var(--${prefix}-link-danger-outline)`,
  'link-danger-shadow-visited': `var(--${prefix}-link-danger-shadow)`,
  'link-danger-text-color-visited': `var(--${prefix}-link-danger-text-color)`
};
