import { DEFAULT_PREFIX } from '../../../mount';
import { prefix } from './constant';

export const defaultCSSVars = {
  // default
  background: '#ffffff',
  'border-width': `var(--${DEFAULT_PREFIX}-border-width)`,
  'border-style': `var(--${DEFAULT_PREFIX}-border-style)`,
  'border-color': '#d9d9d9',
  'border-radius': `var(--${DEFAULT_PREFIX}-border-radius)`,
  outline: 'none',
  shadow: 'none',
  'text-color': `var(--${DEFAULT_PREFIX}-text-color)`,
  // default-active
  'background-active': `var(--${prefix}-background)`,
  'border-width-active': `var(--${prefix}-border-width)`,
  'border-style-active': `var(--${prefix}-border-style)`,
  'border-color-active': `var(--${prefix}-border-color)`,
  'border-radius-active': `var(--${prefix}-border-radius)`,
  'outline-active': `var(--${prefix}-outline)`,
  'shadow-active': `var(--${prefix}-shadow)`,
  'text-color-active': `var(--${DEFAULT_PREFIX}-primary-color-active)`,
  // default-focus
  'background-focus': `var(--${prefix}-background)`,
  'border-width-focus': `var(--${prefix}-border-width)`,
  'border-style-focus': `var(--${prefix}-border-style)`,
  'border-color-focus': `var(--${prefix}-border-color)`,
  'border-radius-focus': `var(--${prefix}-border-radius)`,
  'outline-focus': `var(--${prefix}-outline)`,
  'shadow-focus': `var(--${prefix}-shadow)`,
  'text-color-focus': `var(--${DEFAULT_PREFIX}-primary-color-focus)`,
  // default-hover
  'background-hover': `var(--${prefix}-background)`,
  'border-width-hover': `var(--${prefix}-border-width)`,
  'border-style-hover': `var(--${prefix}-border-style)`,
  'border-color-hover': `var(--${prefix}-border-color)`,
  'border-radius-hover': `var(--${prefix}-border-radius)`,
  'outline-hover': `var(--${prefix}-outline)`,
  'shadow-hover': `var(--${prefix}-shadow)`,
  'text-color-hover': `var(--${DEFAULT_PREFIX}-primary-color-hover)`,
  // default-visited
  'background-visited': `var(--${prefix}-background)`,
  'border-width-visited': `var(--${prefix}-border-width)`,
  'border-style-visited': `var(--${prefix}-border-style)`,
  'border-color-visited': `var(--${prefix}-border-color)`,
  'border-radius-visited': `var(--${prefix}-border-radius)`,
  'outline-visited': `var(--${prefix}-outline)`,
  'shadow-visited': `var(--${prefix}-shadow)`,
  'text-color-visited': `var(--${prefix}-text-color)`
};

export const primaryCSSVars = {
  // primary
  'primary-background': `var(--${DEFAULT_PREFIX}-primary-color)`,
  'primary-border-width': `var(--${DEFAULT_PREFIX}-border-width)`,
  'primary-border-style': `var(--${DEFAULT_PREFIX}-border-style)`,
  'primary-border-color': `var(--${DEFAULT_PREFIX}-primary-color)`,
  'primary-border-radius': `var(--${DEFAULT_PREFIX}-border-radius)`,
  'primary-outline': `var(--${DEFAULT_PREFIX}-primary-color-outline)`,
  'primary-shadow': 'none',
  'primary-text-color': '#ffffff',
  // primary-active
  'primary-background-active': `var(--${DEFAULT_PREFIX}-primary-color-active)`,
  'primary-border-width-active': `var(--${prefix}-primary-border-width)`,
  'primary-border-style-active': `var(--${prefix}-primary-border-style)`,
  'primary-border-color-active': `var(--${DEFAULT_PREFIX}-primary-color-active)`,
  'primary-border-radius-active': `var(--${prefix}-primary-border-radius)`,
  'primary-outline-active': `var(--${prefix}-primary-outline)`,
  'primary-shadow-active': `var(--${prefix}-primary-shadow)`,
  'primary-text-color-active': `var(--${prefix}-primary-text-color)`,
  // primary-focus
  'primary-background-focus': `var(--${DEFAULT_PREFIX}-primary-color-focus)`,
  'primary-border-width-focus': `var(--${prefix}-primary-border-width)`,
  'primary-border-style-focus': `var(--${prefix}-primary-border-style)`,
  'primary-border-color-focus': `var(--${DEFAULT_PREFIX}-primary-color-focus)`,
  'primary-border-radius-focus': `var(--${prefix}-primary-border-radius)`,
  'primary-outline-focus': `var(--${prefix}-primary-outline)`,
  'primary-shadow-focus': `var(--${prefix}-primary-shadow)`,
  'primary-text-color-focus': `var(--${prefix}-primary-text-color)`,
  // primary-hover
  'primary-background-hover': `var(--${DEFAULT_PREFIX}-primary-color-hover)`,
  'primary-border-width-hover': `var(--${prefix}-primary-border-width)`,
  'primary-border-style-hover': `var(--${prefix}-primary-border-style)`,
  'primary-border-color-hover': `var(--${DEFAULT_PREFIX}-primary-color-hover)`,
  'primary-border-radius-hover': `var(--${prefix}-primary-border-radius)`,
  'primary-outline-hover': `var(--${prefix}-primary-outline)`,
  'primary-shadow-hover': `var(--${prefix}-primary-shadow)`,
  'primary-text-color-hover': `var(--${prefix}-primary-text-color)`,
  // primary-visited
  'primary-background-visited': `var(--${prefix}-primary-background)`,
  'primary-border-width-visited': `var(--${prefix}-primary-border-width)`,
  'primary-border-style-visited': `var(--${prefix}-primary-border-style)`,
  'primary-border-color-visited': `var(--${prefix}-primary-border-color)`,
  'primary-border-radius-visited': `var(--${prefix}-primary-border-radius)`,
  'primary-outline-visited': `var(--${prefix}-primary-outline)`,
  'primary-shadow-visited': `var(--${prefix}-primary-shadow)`,
  'primary-text-color-visited': `var(--${prefix}-primary-text-color)`
};

export const linkCSSVars = {
  // link
  'link-background': 'transparent',
  'link-border-width': 'none',
  'link-border-style': 'none',
  'link-border-color': 'none',
  'link-border-radius': 'none',
  'link-outline': 'none',
  'link-shadow': 'none',
  'link-text-color': `var(--${DEFAULT_PREFIX}-primary-color)`,
  // link-active
  'link-background-active': `var(--${prefix}-link-background)`,
  'link-border-width-active': `var(--${prefix}-link-border-width)`,
  'link-border-style-active': `var(--${prefix}-link-border-style)`,
  'link-border-color-active': `var(--${prefix}-link-border-color)`,
  'link-border-radius-active': `var(--${prefix}-link-border-radius)`,
  'link-outline-active': `var(--${prefix}-link-outline)`,
  'link-shadow-active': `var(--${prefix}-link-shadow)`,
  'link-text-color-active': `var(--${prefix}-link-text-color)`,
  // link-focus
  'link-background-focus': `var(--${prefix}-link-background)`,
  'link-border-width-focus': `var(--${prefix}-link-border-width)`,
  'link-border-style-focus': `var(--${prefix}-link-border-style)`,
  'link-border-color-focus': `var(--${prefix}-link-border-color)`,
  'link-border-radius-focus': `var(--${prefix}-link-border-radius)`,
  'link-outline-focus': `var(--${prefix}-link-outline)`,
  'link-shadow-focus': `var(--${prefix}-link-shadow)`,
  'link-text-color-focus': `var(--${prefix}-link-text-color)`,
  // link-hover
  'link-background-hover': `var(--${prefix}-link-background)`,
  'link-border-width-hover': `var(--${prefix}-link-border-width)`,
  'link-border-style-hover': `var(--${prefix}-link-border-style)`,
  'link-border-color-hover': `var(--${prefix}-link-border-color)`,
  'link-border-radius-hover': `var(--${prefix}-link-border-radius)`,
  'link-outline-hover': `var(--${prefix}-link-outline)`,
  'link-shadow-hover': `var(--${prefix}-link-shadow)`,
  'link-text-color-hover': `var(--${prefix}-link-text-color)`,
  // link-visited
  'link-background-visited': `var(--${prefix}-link-background)`,
  'link-border-width-visited': `var(--${prefix}-link-border-width)`,
  'link-border-style-visited': `var(--${prefix}-link-border-style)`,
  'link-border-color-visited': `var(--${prefix}-link-border-color)`,
  'link-border-radius-visited': `var(--${prefix}-link-border-radius)`,
  'link-outline-visited': `var(--${prefix}-link-outline)`,
  'link-shadow-visited': `var(--${prefix}-link-shadow)`,
  'link-text-color-visited': `var(--${prefix}-link-text-color)`
};
